2020-01-04 22:07:03,931 ERROR: Exception on /translate [POST] [in /home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/solar/PycharmProjects/microblog_flask/app/routes.py", line 199, in translate_text
    return jsonify({'text': translate(request.form['text'],
  File "/home/solar/PycharmProjects/microblog_flask/app/translate.py", line 17, in translate
    translation = translate_client.translate(
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/google/cloud/translate_v2/client.py", line 268, in translate
    response = self._connection.api_request(method="POST", path="", data=data)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/google/cloud/_http.py", line 421, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://translation.googleapis.com/language/translate/v2: Invalid Value
2020-01-04 22:08:51,125 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:08:55,256 ERROR: Exception on /translate [POST] [in /home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/app/translate.py", line 17, in translate
    translation = translate_client.translate(
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/google/cloud/translate_v2/client.py", line 268, in translate
    response = self._connection.api_request(method="POST", path="", data=data)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/google/cloud/_http.py", line 421, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://translation.googleapis.com/language/translate/v2: Invalid Value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/solar/PycharmProjects/microblog_flask/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/solar/PycharmProjects/microblog_flask/app/routes.py", line 199, in translate_text
    return jsonify({'text': translate(request.form['text'],
  File "/home/solar/PycharmProjects/microblog_flask/app/translate.py", line 21, in translate
    return _(text, target_language, 'Error: the translation service failed.')
TypeError: gettext() takes 1 positional argument but 3 were given
2020-01-04 22:15:35,026 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:16:39,541 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:18:00,979 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:24:17,764 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:25:47,266 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:35:07,719 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:36:03,420 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:37:16,143 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:42:35,781 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:45:17,598 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
2020-01-04 22:48:36,414 INFO: Microblog startup [in /home/solar/PycharmProjects/microblog_flask/app/__init__.py:54]
